# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "swag init && go build -gcflags='all=-N -l' -o ./tmp/main/engine main.go"
# Binary file yields from `cmd`.
bin = "tmp/main"

# Customize binary, can setup environment variables when run your app.
full_bin = "dlv --listen=:7789 --headless=true --api-version=2 exec ./tmp/main/engine -- http"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "yaml",".env"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "docs"]
# This log file places in your tmp_dir.
log = "air_errors.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 500 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
app = ""
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true