version: "3.7"
services:
  gin-demo:
    container_name: gin-demo
    image: hub.gitlab.nixdev.co/golang-general/gin_basic_app:staging
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:${DB_PORT}
      WAIT_BEFORE_HOSTS: 5
      WAIT_SLEEP_INTERVAL: 3
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
    ports:
      - ${EXPOSE_PORT}:${PORT}
    volumes:
      - ./.env:/app/.env
    restart: on-failure
  mysql:
    container_name: gin-demo-mysql
    restart: on-failure
    image: mysql:8
    env_file:
      - .env
    ports:
      - 3367:3306